POST   http://127.0.0.1:8000/api/v1/auth/registro
Accept: application/json
Content-type: application/json

{
    "name": "userTest",
    "email": "userTest@gmail.com",
    "password": "123456789"
}


POST  http://127.0.0.1:8000/api/v1/auth/login HTTP/1.1
Accept: application/json
Content-type: application/json

{
    "email": "userTest@gmail.com",
    "password": "123456789"
}

### PERFIL

GET  http://127.0.0.1:8000/api/v1/auth/perfil
Accept: application/json
Authorization: : Bearer 1|g857XNIIJDLfZDtlmOS2Ef4Yo2xX8RvVaVdrvokP

{
    "email": "userTest@gmail.com",
    "password": "123456789"
}
### LOGOUT
POST  http://127.0.0.1:8000/api/v1/auth/salir  
Accept: application/json
Authorization: : Bearer 1|g857XNIIJDLfZDtlmOS2Ef4Yo2xX8RvVaVdrvokP
